import type { Metadata } from 'next'
import { Alef } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/sonner"

const alef = Alef({ subsets:['latin'], weight: "400", style: "normal", fallback: ['Monospace', 'helvetica'] })

export const metadata: Metadata = {
  title: 'Portfolio- Mubaraq Akanbi',
  description: 'Generated by Mubaraq Akanbi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={alef.className}>
        <main>{children}</main>
        <Toaster />
        </body>
    </html>
  )
}
